---
language: node_js
node_js:
  - "5.10"

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

install:
  - npm install -g bower
  - bower install
  - npm install

script:
  - ember try $EMBER_TRY_SCENARIO test --skip-cleanup
